# local ssl: https://github.com/Heziode/traefik-v2-https-ssl-localhost
version: '3.8'
services:
  postgres:
    image: "postgres:${MASTER_POSTGRES_VERSION}"
    hostname: postgres_server
    environment:
      POSTGRES_DB: ${MASTER_POSTGRES_DB}
      POSTGRES_USER: ${MASTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MASTER_POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${MASTER_POSTGRES_ROOT_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ytb_sharing-network
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    hostname: api
    ports:
      - '8090:8090'
      - '8000:8000'
    volumes:
      - ./:/app
    networks:
      - ytb_sharing-network
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
      target: build-stage
    hostname: app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
volumes:
  data:
networks:
  ytb_sharing-network:
    name: ytb-sharing-network
    external: true